--- #---------------- laas-auth Deployment ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: laas-auth
  name: laas-auth
  namespace: laas-auth
spec:
  selector:
    matchLabels:
      app: laas-auth
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: laas-auth
    spec:
      containers:
        - name: laas-auth
          image: laas009.azurecr.io/laas-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
