package com.laas.auth.model.entity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserSubscription generated by hbm2java
 */
@Entity
@Table(name = "MandatorySubscription", schema = "Notify")
public class MandatorySubscriptionEntity implements java.io.Serializable {
    private Long seqNo;
	private Long notifyEventSeqNo;
	private Long notifyEventContextSeqNo;
	private String userType;
	private String roleCode;
	private Integer isActivated;
	private String tenantCodeScope;
	private String facilityCodeScope;
	private String forwarderCodeScope;
	private String customerCodeScope;
	private String tenantCodeDefault;

	private String facilityCodeDefault;
	private String forwarderCodeDefault;
	private String customerCodeDefault;

	private Integer isDeletableDefault;
	private Integer isSwitchableDefault;
	
	private String createUser;
	private Date createDt;
	private String updateUser;
	private Date updateDt;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SeqNo", unique = true, nullable = false)
	public Long getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Long seqNo) {
		this.seqNo = seqNo;
	}


	public Long getNotifyEventSeqNo() {
		return this.notifyEventSeqNo;
	}

	public void setNotifyEventSeqNo(Long notifyEventSeqNo) {
		this.notifyEventSeqNo = notifyEventSeqNo;
	}

	public Long getNotifyEventContextSeqNo() {
		return this.notifyEventContextSeqNo;
	}

	public void setNotifyEventContextSeqNo(Long notifyEventContextSeqNo) {
		this.notifyEventContextSeqNo = notifyEventContextSeqNo;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public Integer getIsActivated() {
		return this.isActivated;
	}

	public void setIsActivated(Integer isActivated) {
		this.isActivated = isActivated;
	}

	public String getTenantCodeScope() {
		return this.tenantCodeScope;
	}

	public void setTenantCodeScope(String tenantCodeScope) {
		this.tenantCodeScope = tenantCodeScope;
	}

	public String getFacilityCodeScope() {
		return this.facilityCodeScope;
	}

	public void setFacilityCodeScope(String facilityCodeScope) {
		this.facilityCodeScope = facilityCodeScope;
	}

	public String getForwarderCodeScope() {
		return this.forwarderCodeScope;
	}

	public void setForwarderCodeScope(String forwarderCodeScope) {
		this.forwarderCodeScope = forwarderCodeScope;
	}

	public String getCustomerCodeScope() {
		return this.customerCodeScope;
	}

	public void setCustomerCodeScope(String customerCodeScope) {
		this.customerCodeScope = customerCodeScope;
	}

	public String getTenantCodeDefault() {
		return this.tenantCodeDefault;
	}

	public void setTenantCodeDefault(String tenantCodeDefault) {
		this.tenantCodeDefault = tenantCodeDefault;
	}

	public String getFacilityCodeDefault() {
		return this.facilityCodeDefault;
	}

	public void setFacilityCodeDefault(String facilityCodeDefault) {
		this.facilityCodeDefault = facilityCodeDefault;
	}

	public String getForwarderCodeDefault() {
		return this.forwarderCodeDefault;
	}

	public void setForwarderCodeDefault(String forwarderCodeDefault) {
		this.forwarderCodeDefault = forwarderCodeDefault;
	}

	public String getCustomerCodeDefault() {
		return this.customerCodeDefault;
	}

	public void setCustomerCodeDefault(String customerCodeDefault) {
		this.customerCodeDefault = customerCodeDefault;
	}

	public Integer getIsDeletableDefault() {
		return this.isDeletableDefault;
	}

	public void setIsDeletableDefault(Integer isDeletableDefault) {
		this.isDeletableDefault = isDeletableDefault;
	}

	public Integer getIsSwitchableDefault() {
		return this.isSwitchableDefault;
	}

	public void setIsSwitchableDefault(Integer isSwitchableDefault) {
		this.isSwitchableDefault = isSwitchableDefault;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

}
