package com.laas.auth.model.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotifyEventContext generated by hbm2java
 */
@Entity
@Table(name = "NotifyEventContext", schema = "Notify")
public class NotifyEventContextEntity implements java.io.Serializable {

	private Long seqNo;
	private Long nofityEventSeqNo;
	private String sendingMethod;
	private String contextTemplate;
	private Integer isIncludeAttachment;
	private String defaultAttachmentTypeList;
	private String createUser;
	private Date createDt;
	private String updateUser;
	private Date updateDt;

	@Id

	@Column(name = "SeqNo", unique = true, nullable = false)
	public Long getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Long seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "NofityEventSeqNo")
	public Long getNofityEventSeqNo() {
		return this.nofityEventSeqNo;
	}

	public void setNofityEventSeqNo(Long nofityEventSeqNo) {
		this.nofityEventSeqNo = nofityEventSeqNo;
	}

	@Column(name = "SendingMethod")
	public String getSendingMethod() {
		return this.sendingMethod;
	}

	public void setSendingMethod(String sendingMethod) {
		this.sendingMethod = sendingMethod;
	}

	@Column(name = "ContextTemplate")
	public String getContextTemplate() {
		return this.contextTemplate;
	}

	public void setContextTemplate(String contextTemplate) {
		this.contextTemplate = contextTemplate;
	}

	@Column(name = "IsIncludeAttachment")
	public Integer getIsIncludeAttachment() {
		return this.isIncludeAttachment;
	}

	public void setIsIncludeAttachment(Integer isIncludeAttachment) {
		this.isIncludeAttachment = isIncludeAttachment;
	}

	@Column(name = "DefaultAttachmentTypeList")
	public String getDefaultAttachmentTypeList() {
		return this.defaultAttachmentTypeList;
	}

	public void setDefaultAttachmentTypeList(String defaultAttachmentTypeList) {
		this.defaultAttachmentTypeList = defaultAttachmentTypeList;
	}

	@Column(name = "CreateUser")
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDt", length = 23)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "UpdateUser")
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdateDt", length = 23)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

}

