package com.laas.auth.model.entity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserSubscription generated by hbm2java
 */
@Entity
@Table(name = "UserSubscription", schema = "Notify")
public class UserSubscriptionEntity implements java.io.Serializable {

	private Long seqNo;
	private Long notifyEventSeqNo;
	private Long notifyEventContextSeqNo;
	private String subscriberId;
	private String subscriberUserType;
	private String sendingMethod;
	private String sendingTarget;
	private Integer isIncludeAttachment;
	private String attachmentTypeList;
	private String tenantCode;
	private String facilityCode;
	private String forwarderCode;
	private String customerCode;
	private Integer isByOwner;
	private Integer isDeletable;
	private Integer isActivated;
	private String createUser;
	private Date createDt;
	private String updateUser;
	private Date updateDt;
	private Integer isSwitchable;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SeqNo", unique = true, nullable = false)
	public Long getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Long seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "NotifyEventSeqNo")
	public Long getNotifyEventSeqNo() {
		return this.notifyEventSeqNo;
	}

	public void setNotifyEventSeqNo(Long notifyEventSeqNo) {
		this.notifyEventSeqNo = notifyEventSeqNo;
	}

	@Column(name = "NotifyEventContextSeqNo")
	public Long getNotifyEventContextSeqNo() {
		return this.notifyEventContextSeqNo;
	}

	public void setNotifyEventContextSeqNo(Long notifyEventContextSeqNo) {
		this.notifyEventContextSeqNo = notifyEventContextSeqNo;
	}

	@Column(name = "SubscriberId")
	public String getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(String subscriberId) {
		this.subscriberId = subscriberId;
	}

	@Column(name = "SubscriberUserType")
	public String getSubscriberUserType() {
		return this.subscriberUserType;
	}

	public void setSubscriberUserType(String subscriberUserType) {
		this.subscriberUserType = subscriberUserType;
	}

	@Column(name = "SendingMethod")
	public String getSendingMethod() {
		return this.sendingMethod;
	}

	public void setSendingMethod(String sendingMethod) {
		this.sendingMethod = sendingMethod;
	}

	@Column(name = "SendingTarget")
	public String getSendingTarget() {
		return this.sendingTarget;
	}

	public void setSendingTarget(String sendingTarget) {
		this.sendingTarget = sendingTarget;
	}

	@Column(name = "IsIncludeAttachment")
	public Integer getIsIncludeAttachment() {
		return this.isIncludeAttachment;
	}

	public void setIsIncludeAttachment(Integer isIncludeAttachment) {
		this.isIncludeAttachment = isIncludeAttachment;
	}

	@Column(name = "AttachmentTypeList")
	public String getAttachmentTypeList() {
		return this.attachmentTypeList;
	}

	public void setAttachmentTypeList(String attachmentTypeList) {
		this.attachmentTypeList = attachmentTypeList;
	}

	@Column(name = "TenantCode")
	public String getTenantCode() {
		return this.tenantCode;
	}

	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	@Column(name = "FacilityCode")
	public String getFacilityCode() {
		return this.facilityCode;
	}

	public void setFacilityCode(String facilityCode) {
		this.facilityCode = facilityCode;
	}

	@Column(name = "ForwarderCode")
	public String getForwarderCode() {
		return this.forwarderCode;
	}

	public void setForwarderCode(String forwarderCode) {
		this.forwarderCode = forwarderCode;
	}

	@Column(name = "IsByOwner")
	public Integer getIsByOwner() {
		return this.isByOwner;
	}

	public void setIsByOwner(Integer isByOwner) {
		this.isByOwner = isByOwner;
	}

	@Column(name = "IsDeletable")
	public Integer getIsDeletable() {
		return this.isDeletable;
	}

	public void setIsDeletable(Integer isDeletable) {
		this.isDeletable = isDeletable;
	}

	@Column(name = "IsActivated")
	public Integer getIsActivated() {
		return this.isActivated;
	}

	public void setIsActivated(Integer isActivated) {
		this.isActivated = isActivated;
	}

	@Column(name = "CreateUser")
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDt", length = 23)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "UpdateUser")
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdateDt", length = 23)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "IsSwitchable")
	public Integer getIsSwitchable() {
		return this.isSwitchable;
	}

	public void setIsSwitchable(Integer isSwitchable) {
		this.isSwitchable = isSwitchable;
	}

	public String getCustomerCode() {
		return customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

}

